CREATE TABLE POSTAR
(
    POSTAR_ID   INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    POSTAR_NAME VARCHAR(30),
    CREATED     TIMESTAMP DEFAULT NOW(),
    UPDATED     TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (POSTAR_ID)
);

CREATE TABLE LIST
(
    LIST_ID     INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    POSTAR_ID   INT(10) UNSIGNED NOT NULL,
    ADDRESS     VARCHAR(30),
    CREATED     TIMESTAMP DEFAULT NOW(),
    UPDATED     TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (LIST_ID),
    CONSTRAINT fk_LIST_POSTAR
		FOREIGN KEY (POSTAR_ID) REFERENCES POSTAR (POSTAR_ID)
);

CREATE TABLE USER
(
    USER_ID     INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    NAME   		VARCHAR(30) NOT NULL,
    PASSWORD    VARCHAR(30),
    ROLE	    VARCHAR(30),
    CREATED     TIMESTAMP DEFAULT NOW(),
    UPDATED     TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (USER_ID),
    UNIQUE (NAME)
);

insert into user values(1,'root', 'root', 'ROLE_ADMIN', sysdate(),sysdate());